<div id="content">
    <div id="content-wrap">
        
        <div id="title-bar">
            <h1><?php echo $this->escape($this->title)?></h1>
            <?php echo $this->formmessage;?>
            <ul>
            <?php
                foreach($this->formresponse as $message):
            ?>
                    <li><?php echo $this->escape($message);?></li>
            <?php
                endforeach;
            ?>
            </ul>
        </div>
        
        <div id="body-bar">
            <form accept-charset="utf-8" enctype="multipart/form-data" method="POST" action="<?php echo $this->escape($this->url);?>">
                <div id="or-form">
                    <table>
                        <tr>
                            <td>
                                Name:
                            </td>                            
                            <td>
                                <input id="or-name" type="text" name="or-name"/> 
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Summary:
                            </td>                            
                            <td>
                                <textarea id="or-summary" name="or-summary" rows="10" cols="140"></textarea>
                            </td>
                        </tr>                        
                        <tr>
                            <td>
                                Upload file (100MB max allowed file size):
                            </td>                            
                            <td>
                                <p><input id ="uploads-1" name="uploads-1" type="file"/> 
                                <p><input id ="uploads-2" name="uploads-2" type="file"/> 
                                <p><input id ="uploads-3" name="uploads-3" type="file"/>
                            </td>
                        </tr>
                        
                        <tr>
                            <td>
                                <input id="submit-butt" name="submit-butt" type="submit" value="Submit">
                            </td> 
                        </tr>
                    <table>
                    
                </div>
            </form>
            
        </div>
                
    </div>
</div>


