<div id="content">
    <div id="content-wrap">
        <div id="title-bar">
            <h1>Ordinances </h1>
            <a href="<?php echo $this->url(array('controller'=>'ordinances', 'action'=>'add'), null, true);?>" class="action-button">Add new</a>
        </div>
        <div>
            <table class="block-list" id="ordinances">
                
                <?php
                    echo $this->partialLoop('ordinances/_ordinanceItem.phtml', $this->ordinances);
                ?>
                
            </table>
        </div>
        
    </div>   
</div>