<div id="footer">
    <div id="footer-wrap">
        <div id="footer-top">
            <div class="footer-col grid1">
                <h3>DOWNLOAD</h3>
                <div class="widget">
                    <ul>
                        <li><a href="<?php echo $this->links['ordinances']; ?>">City Ordinances</a></li>
                        <li><a href="<?php echo $this->links['resolutions']; ?>">Resolutions</a></li>
                        <li><a href="<?php echo $this->links['budgets']; ?>">Annual Budgets</a></li>
                        <li><a href="<?php echo $this->links['procurements']; ?>">Annual Procurement Plans</a></li>
                    </ul>
                </div>
            </div>
            <div class="footer-col grid2">
                <h3>DOING BUSINESS IN BACOOR</h3>
                <div class="widget">

                    <ul>
                        <li><a id="bacoor_gov_link" href="">BACOOR.GOV.PH</a></li>
                        <li><a id="dti_link" href="">DTI i-Register</a></li>
                        <li><a id="sec_link" href="">SEC i-Register</a></li>
                    </ul>
                </div>
            </div>
            <div class="footer-col grid3">
                <h3>ADDRESS</h3>
                <div class="widget">
                    <p>City Hall and Capitol Building<br/>
                        Gen. Evangeslista St., 4102 Bacoor,Cavite
                        http://bacoor.gov.ph
                </div>
            </div>
            <div class="footer-col grid4">
                <h3>FOLLOW US ON:</h3>
                <div class="links">
                    <ul>
                        <li>
                            <a href=""><img src="<?php echo $this->baseUrl( 'img/facebook.png' ); ?>"/></a>
                        </li>
                        <li>
                            <a href=""><img src="<?php echo $this->baseUrl( 'img/twitter.png' ); ?>"/></a>
                        </li>
                    </ul>
                </div>
            </div>

            <!--<div class="select-lang">
              <div class="selectform">
                  <form method="get" id="searchform" action="http://bacoor-local">
                      Select your language:
                      <select name="lang" class="selectable">
                          <option value="english">English</option>
                          <option value="filipino" selected>Filipino</option>
                      </select>
                  </form>
              </div>
          </div>-->
        </div>
    </div>

</div>

<div id="footer-bottom">
    <div id="footer-bottom-wrap">
        Copyright 2014 Bacoor City Council. All rights reserved
    </div>
</div>

<script type="text/javascript">
    $( document ).ready( function() {
        $( '#bacoor_gov_link' ).on( 'click', { url: "http://www.bacoor.gov.ph/" },
        function( eventObject ) {
            eventObject.preventDefault();
            window.open( eventObject.data.url );
        } );
        $( '#dti_link' ).on( 'click', { url: "http://www.bnrs.dti.gov.ph/web/guest/registration" },
        function( eventObject ) {
            eventObject.preventDefault();
            window.open( eventObject.data.url );
        } );
        $( '#sec_link' ).on( 'click', { url: "http://iregister.sec.gov.ph/MainServlet" },
        function( eventObject ) {
            eventObject.preventDefault();
            window.open( eventObject.data.url );
        } );
    } );
</script>
<?php echo $this->baseUrl; ?>