<div id="header">
    <div id="header-wrap">
        <div id="header_left">
            <img id="logo-img" alt="Storkflow" src="<?php echo $this->baseUrl( 'img/storkflow.png' ); ?>"/>
        </div>
        <div id="header_right">
            <?php echo $this->partial( "_loginForm.phtml" , array( "form" => $this->layout()->loginForm ) ); ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    $( window ).on( "load resize", function () {
        (function ()
        {
            $( "#logo-img" ).css( { "paddingTop": ($( "#header" ).height() - $( "#logo-img" ).height()) / 2 + "px" } );
        })();
    } ).resize();
</script>