<div class="cssmenu <?php echo $this->useblue; ?>">
    <div class="cssmenu-wrap">
        <?php
        if ( !sizeof( $this->menu ) )
        {
            ?>
            <ul>
                <?php
                if ( $this->usecore )
                {
                    echo $this->partialLoop( '_menuItemNonReg.phtml' , $this->menu );
                }
                else
                {
                    echo $this->partialLoop( '_menuItem.phtml' , $this->menu );
                }
                ?>
            </ul>
            <?php
        }
        ?>

    </div>
</div>