<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <body>
        <?php
        echo $this->partial( "_header.phtml" , array( "user" => $this->layout()->user ) );
        echo $this->partial( "_menu.phtml" , array( "menu" => $this->layout()->menu , "useblue" => "blue" , "usecore" => "core" ));
        echo $this->layout()->content;
        ?>        
    </body>

</html>