<div id="content">
    <div id="content-wrap">
        <div id="title-bar">
            <h1><?php echo $this->escape( $this->title ); ?> </h1>            
        </div>

        <div class="links">
            <ul>
                <?php
                echo $this->partialLoop( 'accounts/_linkItem.phtml' , $this->links );
                ?>
            </ul>
        </div>

        <div>
            <h2>Personal Information</h2> 
            <a class="action-button" href="<?php echo $this->url( array( 'controller' => 'users' , 'action' => 'editmypersonal' ) , null , true ); ?>">
                Edit
            </a>
        </div>
        <div>
            <table>
                <tr>
                    <td>Name:</td>
                    <td><?php echo $this->escape( $this->user->lastname . ", " . $this->user->firstname ); ?></td>
                </tr>
                <tr>
                    <td>Address:</td>
                    <td><?php echo $this->escape( $this->user->address ); ?></td>
                </tr>
                <tr>
                    <td>Contact Numbers:</td>
                    <td><?php echo $this->escape( $this->user->contacts ); ?></td>
                </tr>
                <tr>
                    <td>Email address:</td>
                    <td><?php echo $this->escape( $this->user->email_add ); ?></td>
                </tr>
            </table>
        </div>
        <div>
            <h2>Account Information</h2>
            <a class="action-button" href="<?php echo $this->url( array( 'controller' => 'users' , 'action' => 'editmyaccount' ) , null , true ); ?>">
                Edit
            </a>
        </div>
        <div>
            <table>
                <tr>
                    <td>Username:</td>
                    <td><?php echo $this->escape( $this->user_acc->username ); ?></td>
                </tr>
            </table>
        </div>

        <div>
            <h2>Privilege Information</h2>
            <?php
            if ( $this->canEditOwnPrivilege )
            {
                ?>
                <a class="action-button" href="<?php echo $this->url( array( 'controller' => 'users' , 'action' => 'editmyprivilege' ) , null , true ); ?>">
                    Edit
                </a>
                <?php
            }
            ?>

        </div>
        <div>
            <table>
                <tr>
                    <td>Privilege:</td>
                    <td><?php echo $this->escape( $this->user_role->name ); ?></td>
                </tr>
            </table>
        </div>

        <?php
        if ( $this->hassignature )
        {
            ?>
            <h2>Signature</h2>
            <a class="action-button" href="<?php echo $this->url( array( 'controller' => 'users' , 'action' => 'addsignature' ) , null , true ); ?>">
                Edit
            </a>
            <div>     
                <table>
                    <tr>
                        <td>
                            Signature (small):
                        </td>
                        <td>
                            <?php
                            if ( !is_null( $this->user->signature ) && !empty( $this->user->signature ) )
                            {
                                ?>
                                <img src="<?php echo $this->baseUrl( '/img/users/' . $this->user->id . '/small/' . $this->user->signature ); ?>" alt="No signature" />                                    

                                <?php
                            }
                            else
                            {
                                ?>
                                No signature at the moment. Please upload.
                                <?php
                            }
                            ?> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Signature (tiny):
                        </td>
                        <td>
                            <?php
                            if ( !is_null( $this->user->signature ) && !empty( $this->user->signature ) )
                            {
                                ?>

                                <img src="<?php echo $this->baseUrl( '/img/users/' . $this->user->id . '/tiny/' . $this->user->signature ); ?>" alt="No signature" />                                    
                                <?php
                            }
                            else
                            {
                                ?>
                                No signature at the moment. Please upload.
                                <?php
                            }
                            ?> 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Signature (very tiny):
                        </td>
                        <td>
                            <?php
                            if ( !is_null( $this->user->signature ) && !empty( $this->user->signature ) )
                            {
                                ?>

                                <img src="<?php echo $this->baseUrl( '/img/users/' . $this->user->id . '/verytiny/' . $this->user->signature ); ?>" alt="No signature" />                                    
                                <?php
                            }
                            else
                            {
                                ?>
                                No signature at the moment. Please upload.
                                <?php
                            }
                            ?> 
                        </td>
                    </tr>

                </table>                
            </div>
            <?php
        }
        ?>


    </div>   
</div>