<div id="content">
    <div id="content-wrap">
        
        <div class="links">
            <ul>
                <?php
                echo $this->partialLoop( 'accounts/_linkItem.phtml' , $this->links );
                ?>
            </ul>
        </div>

        <div class="header-div">
            <a class="action-button btn btn-default btn-sm header-glyph" href="<?php echo $this->url( array( 'controller' => 'users' , 'action' => 'editmypersonal' ) , null , true ); ?>">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
            <h2 class="header-glyph" >Personal Information</h2> 
            
        </div>
        <div>
            <table>
                <tr>
                    <td>Name:</td>
                    <td><?php echo $this->escape( $this->user->lastname . ", " . $this->user->firstname ); ?></td>
                </tr>
                <tr>
                    <td>Address:</td>
                    <td><?php echo $this->escape( $this->user->address ); ?></td>
                </tr>
                <tr>
                    <td>Contact Numbers:</td>
                    <td><?php echo $this->escape( $this->user->contacts ); ?></td>
                </tr>
                <tr>
                    <td>Email address:</td>
                    <td><?php echo $this->escape( $this->user->email_add ); ?></td>
                </tr>
            </table>
        </div>
        <div class="header-div" >
            <a class="action-button btn btn-default btn-sm header-glyph" href="<?php echo $this->url( array( 'controller' => 'users' , 'action' => 'editmyaccount' ) , null , true ); ?>">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
            <h2 class="header-glyph" >Account Information</h2>
        </div>
        <div>
            <table>
                <tr>
                    <td>Username:</td>
                    <td><?php echo $this->escape( $this->user_acc->username ); ?></td>
                </tr>
            </table>
        </div>

        <div class="header-div" >
            <?php
            if ( $this->canEditOwnPrivilege )
            {
                ?>
                <a class="action-button btn btn-default btn-sm header-glyph" href="<?php echo $this->url( array( 'controller' => 'users' , 'action' => 'editmyprivilege' ) , null , true ); ?>">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <?php
            }
            ?>
            <h2 class="header-glyph">Privilege Information</h2>
        </div>
        <div>
            <table>
                <tr>
                    <td>Privilege:</td>
                    <td><?php echo $this->escape( $this->user_role->name ); ?></td>
                </tr>
            </table>
        </div>
    </div>   
</div>