<li>
    <a class="action-button" id="<?php echo $this->escape( $this->id ) ?>" href="">
        <?php echo $this->escape( $this->title ); ?>
    </a>
</li>
<script type="text/javascript">
    $( document ).ready( function () {

        $( '#<?php echo $this->escape( $this->id ) ?>' ).on( 'click', function ( e ) {
            e.preventDefault();
            new SimpleAction('', 'dev', '<?php echo $this->id?>');
        } );
    } );
</script>