<div id="content">
    <div id="content-wrap">
        <div id="title-bar">
            <h1><?php echo $this->escape( $this->title ); ?> </h1>            
        </div>

        <div class="links">
            <ul>
                <?php
                echo $this->partialLoop( 'dev/_buttonItem.phtml' , $this->buttons );
                ?>
            </ul>
        </div>

        <div id="button-messages"></div>
    </div>   
</div>

