<?php $sViewFilesUrl = $this->url( array( 'controller' => 'users' , 'action' => 'view' , 'id' => $this->id ) ); ?>
<?php $sEditUrl = $this->url( array( 'controller' => 'users' , 'action' => 'edit' , 'id' => $this->id ) ); ?>

<tr id="n-<?php echo $this->escape( $this->id ); ?>">
    <td>

        <div class="bl-title">
            <h2><a href="<?php echo $sViewFilesUrl; ?>"><?php echo $this->escape( $this->name ); ?></a></h2>
            <p><?php
                $sGuest = "anonymous";
                if ( $this->escape( $this->user_created ) )
                {
                    $sGuest = $this->escape( $this->user_created );
                }
                echo $this->escape( $this->date_created ) . " by " . $sGuest;
                ?>
            <p>Email address: <?php echo $this->escape( $this->email_add ) ?>, Contact number: <?php echo $this->escape( $this->contacts ); ?>

        </div>
        <div class="links">
            <ul>
                <?php
                if ( $this->edit )
                {
                    ?>
                    <li>
                        <a href="<?php echo $sEditUrl; ?>" class="action-button" id="edit-butt-<?php echo $this->id ?>">
                            Edit
                        </a>
                    </li>  
                    <?php
                }
                ?>
                <?php
                if ( $this->delete )
                {
                    ?>
                    <li>
                        <a href="" class="action-button" id="del-butt-<?php echo $this->id ?>">
                            Delete
                        </a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if ( $this->approve && !$this->alreadyapproved )
                {
                    ?>
                    <li>
                        <a href="" class="action-button" id="approve-butt-<?php echo $this->id ?>">
                            Approve
                        </a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if ( $this->deny )
                {
                    ?>
                    <li>
                        <a href="" class="action-button" id="deny-butt-<?php echo $this->id ?>">
                            Deny
                        </a>
                    </li>
                    <?php
                }
                ?>

            </ul>
            <div id="approve-mess-<?php echo $this->id; ?>"></div>
        </div>

    </td>
</tr>
<script type="text/javascript">
    $( document ).ready( function () {
<?php
if ( $this->delete )
{
    ?>
            var deletefunc = function () {
                new Delete( '<?php echo $this->baseUrl(); ?>', 'users', 'delete', '<?php echo $this->id ?>', 'users' );
            };
            $( "#del-butt-<?php echo $this->id ?>" ).on( "click", function ( eventData )
            {
                new Confirm( 'Confirm', 'Are you sure you want to delete the user details?', 'Yes', deletefunc );
                eventData.preventDefault();
            } );
    <?php
}
?>

<?php
if ( $this->approve && !$this->alreadyapproved )
{
    ?>
            var approve = function () {
                new PostThenDeleteTableRow( '<?php echo $this->baseUrl(); ?>', 'users', 'approve', '<?php echo $this->id ?>', 'users' );
            };
            $( "#approve-butt-<?php echo $this->id ?>" ).on( "click", function ( eventData )
            {
                new Confirm( 'Confirm', 'Are you sure you want to approve the user request?', 'Yes', approve );
                eventData.preventDefault();
            } );
    <?php
}
?>

<?php
if ( $this->deny )
{
    ?>
            var deny = function () {
                new PostThenDeleteTableRow( '<?php echo $this->baseUrl(); ?>', 'users', 'deny', '<?php echo $this->id ?>', 'users' );
            };
            $( "#deny-butt-<?php echo $this->id ?>" ).on( "click", function ( eventData )
            {
                new Confirm( 'Confirm', 'Are you sure you want to deny the user request?', 'Yes', deny );
                eventData.preventDefault();
            } );
    <?php
}
?>
    } );

</script>
