<?php $viewUrl = $this->url( array( 'controller' => 'users' , 'action' => 'view' , 'id' => $this->sys_id ) ); ?>
<?php $editUrl = $this->url( array( 'controller' => 'users' , 'action' => 'edit' , 'id' => $this->sys_id ) ); ?>

<tr id="user-<?php echo $this->escape( $this->sys_id ); ?>">
    <td>

        <div class="bl-title">
            <h2><a href="<?php echo $viewUrl; ?>"><?php echo $this->escape( $this->name ); ?></a></h2>
            <p><?php
                $guest = "Anonymous";
                if ( $this->escape( $this->user_created ) )
                {
                    $guest = $this->escape( $this->user_created );
                }
                echo "Added last: " . $this->escape( $this->date_created ) . " by " . $guest;
                ?>
            <p>Email address: <?php echo $this->escape( $this->email_add ) ?>, Contact number: <?php echo $this->escape( $this->contacts ); ?>

        </div>
        <div class="links">
            <ul>
                <?php
                if ( $this->delete )
                {
                    ?>
                    <li>
                        <a href="" class="action-button" id="del-butt-<?php echo $this->sys_id ?>">
                            Delete
                        </a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if ( $this->approve && !$this->alreadyapproved )
                {
                    ?>
                    <li>
                        <a href="" class="action-button" id="approve-butt-<?php echo $this->sys_id ?>">
                            Approve
                        </a>
                    </li>
                    <?php
                }
                ?>
                <?php
                if ( $this->deny )
                {
                    ?>
                    <li>
                        <a href="" class="action-button" id="deny-butt-<?php echo $this->sys_id ?>">
                            Deny
                        </a>
                    </li>
                    <?php
                }
                ?>

            </ul>
            <div id="approve-mess-<?php echo $this->sys_id; ?>"></div>
        </div>

    </td>
</tr>
<script type="text/javascript">
    $( document ).ready( function () {
<?php
if ( $this->delete )
{
    ?>            
            $( "#del-butt-<?php echo $this->sys_id ?>" ).on( "click", function ( eventData )
            {
                new Confirm( 'Confirm', 'Are you sure you want to delete the user?', 'Yes', function () {
                    new NewDelete( {
                        url: "<?php echo $this->baseUrl(); ?>",
                        controller: "users",
                        action: "delete",
                        id: "<?php echo $this->sys_id ?>",
                        onSuccess: function () {
                            $( "#user-<?php echo $this->sys_id ?>" ).remove();
                        }
                    } );
                } );
                eventData.preventDefault();
            } );
    <?php
}
?>

<?php
if ( $this->approve && !$this->alreadyapproved )
{
    ?>
            var approve = function () {
                new PostThenDeleteTableRow( '<?php echo $this->baseUrl(); ?>', 'users', 'approve', '<?php echo $this->sys_id ?>', 'users' );
            };
            $( "#approve-butt-<?php echo $this->sys_id ?>" ).on( "click", function ( eventData )
            {
                new Confirm( 'Confirm', 'Are you sure you want to approve the user request?', 'Yes', approve );
                eventData.preventDefault();
            } );
    <?php
}
?>

<?php
if ( $this->deny )
{
    ?>
            var deny = function () {
                new PostThenDeleteTableRow( '<?php echo $this->baseUrl(); ?>', 'users', 'deny', '<?php echo $this->sys_id ?>', 'users' );
            };
            $( "#deny-butt-<?php echo $this->sys_id ?>" ).on( "click", function ( eventData )
            {
                new Confirm( 'Confirm', 'Are you sure you want to deny the user request?', 'Yes', deny );
                eventData.preventDefault();
            } );
    <?php
}
?>
    } );

</script>
