<div id="content">
    <div id="content-wrap">

        <div id="title-bar">
            <h1><?php echo $this->escape( $this->title ) ?></h1>
            <?php echo $this->formmessage; ?>
            <ul>
                <?php
                foreach ( $this->formresponse as $message ):
                    ?>
                    <li><?php echo $this->escape( $message ); ?></li>
                    <?php
                endforeach;
                ?>
            </ul>
        </div>

        <div id="body-bar">
            <form accept-charset="utf-8" enctype="multipart/form-data" method="POST" action="">
                <?php
                if ( !is_null( $this->user->signature ) && !empty( $this->user->signature ) )
                {
                    ?>
                    <div>
                        <h3>Original Size</h3>
                        <img src="<?php echo $this->baseUrl( 'img/users/' . $this->user->id . '/' . $this->user->signature ); ?>" alt="No signature" />
                    </div>

                    <div>
                        <h3>400x400 Size</h3>
                        <img src="<?php echo $this->baseUrl( 'img/users/' . $this->user->id . '/small/' . $this->user->signature ); ?>" alt="No signature" />
                    </div>

                    <div>
                        <h3>100x100 Size</h3>
                        <img src="<?php echo $this->baseUrl( 'img/users/' . $this->user->id . '/tiny/' . $this->user->signature ); ?>" alt="No signature" />
                    </div>

                    <div>
                        <h3>50x50 Size</h3>
                        <img src="<?php echo $this->baseUrl( 'img/users/' . $this->user->id . '/verytiny/' . $this->user->signature ); ?>" alt="No signature" />
                    </div>

                    <?php
                }
                ?>
                <div id="or-form">
                    <table>                       
                        <tr>
                            <td>
                                Upload file to add/change signature:
                            </td>                            
                            <td>
                                <p><input id ="signature" name="signature" type="file"/>
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <input id="submit-butt" name="submit-butt" type="submit" value="Submit">
                            </td> 
                        </tr>
                        <table>                    
                            </div>
                            </form>

                            </div>

                            </div>
                            </div>


