<ul class="bxslider"></ul>

<script type="text/javascript">
    $( document ).ready( function() {

        $( '.bxslider' ).append(
                $( '<li/>' ).append( $( '<img>', { src: '<?php echo $this->baseUrl( 'img/slider1.jpg' ); ?>' } ) )
                ).append(
                $( '<li/>' ).append( $( '<img>', { src: '<?php echo $this->baseUrl( 'img/slider2.jpg' ); ?>' } ) )
                );

        $( '.bxslider' ).bxSlider( {
            auto: true,
            autoControls: true,
            pause: 6000
        } );
    } );
</script>