<?php $sViewNewsUrl = $this->url(array('controller'=>'news', 'action'=>'view', 'id'=>$this->id)); ?>

<tr id="n-<?php echo $this->escape($this->id);?>" >
    
    <td>
        <a href="<?php echo $sViewNewsUrl?>">
            <?php echo $this->escape($this->title); ?>
        </a>
    </td>

    <td>
        <?php echo $this->escape($this->body);?>
    </td>

    <td>
        <?php echo $this->escape($this->date_created);?>
    </td>
    
    <td>
        <?php echo $this->escape($this->user_created);?>
    </td>
    
    <td>
        <?php echo $this->escape($this->date_last_modified);?>
    </td>
    
    <td>
        <?php echo $this->escape($this->user_last_modified);?>
    </td>
    
    <td>
        <span><a href="#">Delete</a></span>
    </td>
</tr>
