<div id="content">
    <div id="content-wrap">
        <h1>Add Files</h1>

        <?php
        if ( !is_null( $this->message ) && !empty( $this->message ) )
        {
            ?>
            <div id="flashmessage" class="flashmessage">
                <ul>
                    <li><?= $this->message; ?></li>
                </ul>
            </div>
            <?php
        }
        ?>

        <div id="add-files">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    $( document ).ready( function() {

        var saveEdit = function() {
            $( "#saveAdd" ).submit();
        };

        $( "#Save" ).on( 'click', function( eventData )
        {
            new Confirm( 'Confirm', 'Are you sure you want to save the changes?', 'Yes', saveEdit );
            eventData.preventDefault();
        } );

    } );
</script> 