<div id="content">
    <div id="content-wrap">
        <h1>Edit Legislation</h1>

        <?php
        if ( !is_null( $this->message ) && !empty( $this->message ) )
        {
            ?>
            <div id="flashmessage" class="flashmessage">
                <ul>
                    <li><?= $this->message; ?></li>
                </ul>
            </div>
            <?php
        }
        ?>

        <div id="edit-legislation">
            <?php echo $this->form; ?>
        </div>

        <div class="file-row"></div>
    </div>
</div>

<script type="text/javascript">
    $( document ).ready( function () {

        var saveEdit = function () {
            $( "#saveEdit" ).submit();
        };

        $( "#Save" ).on( 'click', function ( eventData )
        {
            new Confirm( 'Confirm', 'Are you sure you want to save the changes?', 'Yes', saveEdit );
            eventData.preventDefault();
        } );

        var files = <?php echo json_encode( $this->files ) ?>;
        var ul = $( "<ul/>" ).css( {
            'list-style': 'none',
            'margin': 0,
            'padding': 0,
            'font-size': 12,
            'font-family': 'Georgia'
        } );

        var deleteFile = function ( id, ordinanceId, filename ) {
            new DeleteOrdinanceFile( '<?php echo $this->baseUrl(); ?>', 'legislation', 'deletebuprocfile', id, ordinanceId, filename );
        };

        for ( var i = 0; i < files.length; i++ )
        {
            var a = $( "<a/>" ).attr( "href", files[i].url ).attr( "id", "file-item-" + files[i].id )
                    .css( { 'padding-right': 10 } )
                    .append( files[i].filename );
            var li = $( "<li/>" ).attr( "id", "li-" + files[i].id )
                    .css( { 'padding': 5 } );
            var deleteButt = $( '<a/>', { 'class': 'action-button', href: '', id: 'i-' + files[i].id } ).append( 'x' )
                    .on( 'click', { id: files[i].id, ordinanceId: files[i].ordinance_id, filename: files[i].filename }, function ( eventData )
                    {
                        new Confirm( 'Confirm', 'Are you sure you want to delete the file?', 'Yes', function ()
                        {
                            deleteFile( eventData.data.id, eventData.data.ordinanceId, eventData.data.filename );
                        } );
                        eventData.preventDefault();
                    } );

            li.append( a ).append( $( "<span/>" ).append( deleteButt ) );
            ul.append( li );
        }
        $( ".file-row" ).append( ul );

    } );
</script> 