<div class="colmask threecol">
    <div class="content-wrap">
        <div class="colmid">
            <div class="colleft">
                <div class="col1">
                    <div id="title-category-bar">
                        <h1><?php echo $this->category; ?></h1>
                    </div>
                    <div id="title-bar">
                        <h2>City <?php echo ucwords( strtolower( $this->ordinance->type ) ); ?> No. <?php echo $this->ordinance->id; ?></h2>
                        <h2 id="article-title"><?php echo nl2br( htmlentities( $this->ordinance->name ) ) ?></h2>                        
                    </div>

                    <div class="links">
                        <?php
                        if ( $this->showDownloadButton )
                        {
                            ?>
                            <ul>
                                <li>
                                    <a href="#" class="action-button" id="dl-<?php echo $this->ordinance->id; ?>">
                                        Download
                                    </a>
                                </li>
                            </ul>
                            <?php
                        }
                        ?>

                    </div>

                    <div id="content">
                        <table class="block-list" id="ordinance">
                            <tr id="n-<?php echo $this->escape( $this->ordinance->id ); ?>">
                                <td width="60%">
                                    <div class="bl-summary">
                                        <p><?php echo nl2br( htmlentities( $this->ordinance->summary ) ); ?>
                                    </div>
                                    <div class="bl-signed">
                                        <p><span class="bold">Signed by:</span>
                                        <table class="approvals" id="approvals">

                                            <?php
                                            if ( !is_null( $this->approvals ) && !empty( $this->approvals ) )
                                            {
                                                $superadmin = null;
                                                $superuser = null;
                                                $district1Councilors = null;
                                                $district2Councilors = null;
                                                for ( $i = 0 , $j = count( $this->approvals ); $i < $j; $i++ )
                                                {
                                                    if ( ( int ) $this->approvals[ $i ][ 'user_id' ] === SiteConstants::$SUPERADMIN_ID )
                                                    {
                                                        $superadmin[] = $this->approvals[ $i ];
                                                    }
                                                    else if ( ( int ) $this->approvals[ $i ][ 'user_id' ] === SiteConstants::$SUPERUSER_ID )
                                                    {
                                                        $superuser[] = $this->approvals[ $i ];
                                                    }
                                                    else if ( ( int ) $this->approvals[ $i ][ 'district' ] === 1 )
                                                    {
                                                        $district1Councilors[] = $this->approvals[ $i ];
                                                    }
                                                    else if ( ( int ) $this->approvals[ $i ][ 'district' ] === 2 )
                                                    {
                                                        $district2Councilors[] = $this->approvals[ $i ];
                                                    }
                                                }

                                                if ( !is_null( $superadmin ) )
                                                {
                                                    for ( $i = 0; $i < count( $superadmin ); $i++ )
                                                    {
                                                        ?>
                                                        <tr>
                                                            <td id="n-<?php echo $this->escape( $superadmin[ $i ][ 'id' ] ); ?>">
                                                                <span><?php echo $this->escape( $superadmin[ $i ][ 'firstname' ] . ' ' . $superadmin[ $i ][ 'lastname' ] ); ?></span>
                                                                <span><img src="<?php echo $this->baseUrl( 'img/users/' . $superadmin[ $i ][ 'user_id' ] . '/tiny/' . $superadmin[ $i ][ 'signature' ] ); ?>" alt="(No signature)" /></span>
                                                            </td>
                                                            <td>&nbsp;</td>
                                                        </tr>
                                                        <?php
                                                    }
                                                }
                                                if ( !is_null( $superuser ) )
                                                {
                                                    for ( $i = 0; $i < count( $superuser ); $i++ )
                                                    {
                                                        //TODO: adjust javascript for this in approve button                                                         
                                                        ?>
                                                        <tr>
                                                            
                                                            <td id="n-<?php echo $this->escape( $superuser[ $i ][ 'id' ] ); ?>">
                                                                <span><?php echo $this->escape( $superuser[ $i ][ 'firstname' ] . ' ' . $superuser[ $i ][ 'lastname' ] ); ?></span>
                                                                <span><img src="<?php echo $this->baseUrl( 'img/users/' . $superuser[ $i ][ 'user_id' ] . '/tiny/' . $superuser[ $i ][ 'signature' ] ); ?>" alt="(No signature)" /></span>
                                                            </td>
                                                            <td>&nbsp;</td>
                                                        </tr>
                                                        <?php
                                                    }
                                                }

                                                if ( !is_null( $district1Councilors ) && !is_null( $district2Councilors ) )
                                                {
                                                    ?>
                                                    <tr>
                                                        <td>
                                                            <h4>DISTRICT 1<h4>
                                                        </td>
                                                        <td>
                                                            <h4>DISTRICT 2<h4>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                }
                                                else if ( !is_null( $district1Councilors ) )
                                                {
                                                    ?>
                                                    <tr>
                                                        <td>
                                                            <h4>DISTRICT 1<h4>
                                                        </td>
                                                        <td>
                                                            &nbsp;
                                                        </td>
                                                    </tr>
                                                    <?php
                                                }
                                                else if ( !is_null( $district2Councilors ) )
                                                {
                                                    ?>
                                                    <tr>
                                                        <td>
                                                            &nbsp;                                                            
                                                        </td>
                                                        <td>
                                                            <h4>DISTRICT 2<h4>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                }

                                                $councilors1Count = count( $district1Councilors );
                                                $councilors2Count = count( $district2Councilors );
                                                $count = $councilors1Count < $councilors2Count ?
                                                        $councilors1Count : $councilors2Count;
                                                $diff = $councilors1Count - $councilors2Count;
                                                $i = 0;
                                                for (; $i < $count; $i++ )
                                                {
                                                    ?>
                                                    <tr>
                                                        <td id="n-<?php echo $this->escape( $district1Councilors[ $i ][ 'id' ] ); ?>">
                                                            <span><?php echo $this->escape( $district1Councilors[ $i ][ 'firstname' ] . ' ' . $district1Councilors[ $i ][ 'lastname' ] ); ?></span>
                                                            <span><img src="<?php echo $this->baseUrl( 'img/users/' . $district1Councilors[ $i ][ 'user_id' ] . '/tiny/' . $district1Councilors[ $i ][ 'signature' ] ); ?>" alt="(No signature)" /></span>
                                                        </td>
                                                        <td id="n-<?php echo $this->escape( $district2Councilors[ $i ][ 'id' ] ); ?>">
                                                            <span><?php echo $this->escape( $district2Councilors[ $i ][ 'firstname' ] . ' ' . $district2Councilors[ $i ][ 'lastname' ] ); ?></span>
                                                            <span><img src="<?php echo $this->baseUrl( 'img/users/' . $district2Councilors[ $i ][ 'user_id' ] . '/tiny/' . $district2Councilors[ $i ][ 'signature' ] ); ?>" alt="(No signature)" /></span>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                }
                                                for ( $j = $i; $j < $i + abs( $diff ); $j++ )
                                                {
                                                    if ( $diff < 0 )
                                                    {
                                                        ?>
                                                        <tr>
                                                            <td>&nbsp;</td>
                                                            <td id="n-<?php echo $this->escape( $district2Councilors[ $j ][ 'id' ] ); ?>">
                                                                <span><?php echo $this->escape( $district2Councilors[ $j ][ 'firstname' ] . ' ' . $district2Councilors[ $j ][ 'lastname' ] ); ?></span>
                                                                <span><img src="<?php echo $this->baseUrl( 'img/users/' . $district2Councilors[ $j ][ 'user_id' ] . '/tiny/' . $district2Councilors[ $j ][ 'signature' ] ); ?>" alt="(No signature)" /></span>
                                                            </td>
                                                        </tr>
                                                        <?php
                                                    }
                                                    else if ( $diff > 0 )
                                                    {
                                                        ?>
                                                        <tr>
                                                            <td id="n-<?php echo $this->escape( $district1Councilors[ $i ][ 'id' ] ); ?>">
                                                                <span><?php echo $this->escape( $district1Councilors[ $j ][ 'firstname' ] . ' ' . $district1Councilors[ $j ][ 'lastname' ] ); ?></span>
                                                                <span><img src="<?php echo $this->baseUrl( 'img/users/' . $district1Councilors[ $j ][ 'user_id' ] . '/tiny/' . $district1Councilors[ $j ][ 'signature' ] ); ?>" alt="(No signature)" /></span>
                                                            </td>
                                                            <td>&nbsp;</td>
                                                        </tr>
                                                        <?php
                                                    }
                                                }
                                            }
                                            else
                                            {
                                                ?>
                                                <tr><td><p>There are no approvals for this ordinance.</td></tr>
                                                <?php
                                            }
                                            ?>
                                        </table>
                                    </div>
                                    <div class="links">
                                        <ul>
                                            <?php
                                            if ( $this->showEditButton )
                                            {
                                                ?>
                                                <li>
                                                    <a href="<?php echo $this->url( array( 'controller' => 'legislation' , 'action' => 'edit' , 'id' => $this->ordinance->id ) , null , true ); ?>" class="action-button">Edit</a>
                                                </li>
                                                <?php
                                            }
                                            ?>
                                            <?php
                                            if ( $this->showPublishButton )
                                            {
                                                ?>
                                                <li id="approve-butt-<?php echo $this->ordinance->id ?>">
                                                    <a href="" class="action-button">
                                                        Approve and Publish
                                                    </a> 
                                                </li>
                                                <?php
                                            }
                                            else if ( $this->showApproveButton )
                                            {
                                                ?>
                                                <li id="approve-butt-<?php echo $this->ordinance->id ?>">
                                                    <a href="" class="action-button">
                                                        Approve
                                                    </a> 
                                                </li>
                                                <?php
                                            }
                                            
                                            ?>
                                        </ul>
                                        <div id="appr-mess-<?php echo $this->ordinance->id; ?>">
                                            <?php
                                            if ( $this->alreadyApproved )
                                            {
                                                ?>                    
                                                <h4>You have already signed this ordinance.</h4>
                                                <?php
                                            }
                                            ?>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="col2">
                    <div id="visit">
                        <a id="visit_link" href="">
                            <img id="banner-img" alt="Bacoor City Government" src="<?php echo $this->baseUrl( 'img/bacoor.png' ); ?>" width="100%"/>
                        </a>
                    </div>
                    <div id="ordinances-header">
                        <div id="ordinances-header-content">
                            City Ordinances
                        </div>
                    </div>
                    <div id="ordinances-list">
                        <ul>
                            <?php
                            echo $this->partialLoop( 'index/_ordinanceItem.phtml' , $this->ordinancesside );
                            ?>
                        </ul>
                    </div>
                    <!-- Column 2 end -->
                </div>
                <div class="col3">
                    <!-- Column 3 start -->
                    <div id="ads">
                        <a href="">
                            <img src=<?php echo $this->baseUrl( 'img/vote.png' ); ?> alt="Vote!" width="100%"/>
                        </a>
                    </div>
                    <div id="map-header">
                        <div id="map-header-content">
                            Polls
                        </div>
                    </div>
                    <div id="map">
                        <div id="poll-form" class="poll-form">


                            <?php
                            if ( !is_null( $this->poll ) && !empty( $this->poll ) )
                            {
                                ?>
                                <div id="anosatinginmo" class="bold">
                                    ANO SA TINGIN MO?
                                </div>
                                <div id="poll-question-<?php echo $this->poll[ 'q_id' ]; ?>" class="poll-question">
                                    <?php echo $this->escape( $this->poll[ 'question' ] ); ?>                          
                                </div>

                                <?php
                                if ( $this->vote )
                                {
                                    ?>
                                    <div id="poll-options-<?php echo $this->poll[ 'q_id' ]; ?>" class="poll-options">
                                        <ul>
                                            <?php
                                            $i = 0;
                                            foreach ( $this->poll[ 'options' ] as $option )
                                            {
                                                ?>
                                                <li>
                                                    <?php
                                                    if ( $i == 0 )
                                                    {
                                                        ?>
                                                        <input type="radio" name="poll-radio" checked="true" value="<?php echo $this->escape( $option[ 'opt_id' ] ); ?>" class="signup-radio"/>
                                                        <?php
                                                    }
                                                    else
                                                    {
                                                        ?>
                                                        <input type="radio" name="poll-radio" value="<?php echo $this->escape( $option[ 'opt_id' ] ); ?>" class="signup-radio"/>
                                                        <?php
                                                    }
                                                    ?>

                                                    <?php echo $this->escape( $option[ 'option' ] ); ?>
                                                </li>
                                                <?php
                                                $i++;
                                            }
                                            ?>
                                        </ul>
                                    </div>
                                    <?php
                                }
                                else
                                {
                                    ?>

                                    <div id="poll-options-<?php echo $this->poll[ 'q_id' ]; ?>" class="poll-options">
                                        <ul>
                                            <?php
                                            $i = 0;
                                            foreach ( $this->poll[ 'options' ] as $option )
                                            {
                                                ?>
                                                <li>                                                    
                                                    <?php echo $this->escape( ($i + 1) . '. ' . $option[ 'option' ] ); ?>
                                                </li>
                                                <?php
                                                $i++;
                                            }
                                            ?>
                                        </ul>
                                    </div>                                       
                                    <?php
                                }
                                ?>


                                <div class="links">

                                    <ul>
                                        <?php
                                        if ( !$this->vote )
                                        {
                                            ?>
                                            <li>Log in to vote.</li>
                                            <?php
                                        }
                                        else
                                        {
                                            ?>
                                            <li id="poll-button-changer"></li>
                                            <?php
                                        }
                                        ?>
                                        <li><span><a class="action-button" href="<?php echo $this->baseUrl( 'polls/published' ); ?>">Show all</a></span></li>
                                    </ul>
                                </div>   
                                <?php
                            }
                            else
                            {
                                ?>
                                <div class="links">

                                    <ul>
                                        <li>Thanks for voting on all polls!</li>
                                        <li><span><a class="action-button" href="<?php echo $this->baseUrl( 'polls/published' ); ?>">Show all</a></span></li>
                                    </ul>
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $( document ).ready( function () {

        $( '#visit_link' ).on( 'click', { url: "http://www.cavite.gov.ph/home/index.php/cities-and-municipalities/district-ii/bacoor-city" },
        function ( eventObject ) {
            window.open( eventObject.data.url );
            return false;
        } );

<?php
if ( !is_null( $this->poll ) && !empty( $this->poll ) )
{
    if ( $this->vote )
    {
        ?>
                $( '#poll-button-changer' ).empty().append( $( '<span/>' ).append( $( '<a/>', {
                    html: "Vote",
                    href: "",
                    "class": "action-button"
                } ) ) );

                $( '#poll-button-changer' ).find( 'a' ).on( 'click', {
                    url: '<?php echo $this->baseUrl(); ?>',
                    controller: 'polls',
                    action: 'vote',
                    questionId: '<?php echo $this->poll[ 'q_id' ] ?>',
                    radioGroupName: 'poll-radio',
                    containerName: 'poll-options',
                    buttonContainerName: 'poll-button-changer'
                }, function ( event ) {
                    event.preventDefault();
                    new Vote( event.data.url, event.data.controller, event.data.action,
                            event.data.questionId, event.data.radioGroupName,
                            event.data.containerName, event.data.buttonContainerName );
                } );
        <?php
    }
}
?>

<?php
if ( $this->showApproveButton )
{
    ?>
            var approve = function () {
                new Approve( '<?php echo $this->baseUrl(); ?>', 'legislation', 'approve', '<?php echo $this->ordinance->id ?>' );
            };

            $( "#approve-butt-<?php echo $this->ordinance->id ?>" ).on( "click", function ( eventData )
            {
                new Confirm( 'Confirm', 'Are you sure you want to approve the legislation?', 'Yes', approve );
                eventData.preventDefault();
            } );

    <?php
}
?>
<?php
if ( $this->showPublishButton )
{
    ?>
            var publish = function () {
                new Approve( '<?php echo $this->baseUrl(); ?>', 'legislation', 'newpublish', '<?php echo $this->ordinance->id ?>' );
            };

            $( "#approve-butt-<?php echo $this->ordinance->id ?>" ).on( "click", function ( eventData )
            {
                new Confirm( 'Confirm', 'Are you sure you want to approve and publish the legislation?', 'Yes', publish );
                eventData.preventDefault();
            } );
    <?php
}
?>

<?php
if ( $this->showDownloadButton )
{
    ?>
            //download button
            ordinances = [ ];
            ordinances['dl-<?php echo $this->ordinance->id; ?>'] = {
                name: <?php echo json_encode( $this->ordinance->name ); ?>,
                logo: '<?php echo $this->logoURI ?>',
                content: <?php echo json_encode( $this->ordinance->summary ); ?>
            };

            var councilors = [ ], councilors1 = [ ], councilors2 = [ ], superuser = [ ], superadmin = [ ];
    <?php
    foreach ( $this->councilors as $councilor )
    {
        ?>
                var temp = { };
                temp['name'] = <?php echo json_encode( $councilor[ 'name' ] ); ?>;
        <?php
        if ( array_key_exists( 'datauri' , $councilor ) )
        {
            ?>
                    temp['datauri'] = '<?php echo $councilor[ 'datauri' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauri'] = '';
            <?php
        }
        ?>

        <?php
        if ( array_key_exists( 'datauriwidth' , $councilor ) )
        {
            ?>
                    temp['datauriwidth'] = '<?php echo $councilor[ 'datauriwidth' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauriwidth'] = 0;
            <?php
        }
        ?>

        <?php
        if ( array_key_exists( 'datauriheight' , $councilor ) )
        {
            ?>
                    temp['datauriheight'] = '<?php echo $councilor[ 'datauriheight' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauriheight'] = 0;
            <?php
        }
        ?>
                councilors.push( temp );
        <?php
    }
    ?>

    <?php
    foreach ( $this->councilors1 as $councilor )
    {
        ?>
                var temp = { };
                temp['name'] = <?php echo json_encode( $councilor[ 'name' ] ); ?>;
        <?php
        if ( array_key_exists( 'datauri' , $councilor ) )
        {
            ?>
                    temp['datauri'] = '<?php echo $councilor[ 'datauri' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauri'] = '';
            <?php
        }
        ?>

        <?php
        if ( array_key_exists( 'datauriwidth' , $councilor ) )
        {
            ?>
                    temp['datauriwidth'] = '<?php echo $councilor[ 'datauriwidth' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauriwidth'] = 0;
            <?php
        }
        ?>

        <?php
        if ( array_key_exists( 'datauriheight' , $councilor ) )
        {
            ?>
                    temp['datauriheight'] = '<?php echo $councilor[ 'datauriheight' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauriheight'] = 0;
            <?php
        }
        ?>
                councilors1.push( temp );
        <?php
    }
    ?>

    <?php
    foreach ( $this->councilors2 as $councilor )
    {
        ?>
                var temp = { };
                temp['name'] = <?php echo json_encode( $councilor[ 'name' ] ); ?>;
        <?php
        if ( array_key_exists( 'datauri' , $councilor ) )
        {
            ?>
                    temp['datauri'] = '<?php echo $councilor[ 'datauri' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauri'] = '';
            <?php
        }
        ?>

        <?php
        if ( array_key_exists( 'datauriwidth' , $councilor ) )
        {
            ?>
                    temp['datauriwidth'] = '<?php echo $councilor[ 'datauriwidth' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauriwidth'] = 0;
            <?php
        }
        ?>

        <?php
        if ( array_key_exists( 'datauriheight' , $councilor ) )
        {
            ?>
                    temp['datauriheight'] = '<?php echo $councilor[ 'datauriheight' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauriheight'] = 0;
            <?php
        }
        ?>
                councilors2.push( temp );
        <?php
    }
    ?>

    <?php
    foreach ( $this->superuser as $superuser )
    {
        ?>
                var temp = { };
                temp['name'] = <?php echo json_encode( $superuser[ 'name' ] ); ?>;
        <?php
        if ( array_key_exists( 'datauri' , $superuser ) )
        {
            ?>
                    temp['datauri'] = '<?php echo $superuser[ 'datauri' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauri'] = '';
            <?php
        }
        ?>

        <?php
        if ( array_key_exists( 'datauriwidth' , $superuser ) )
        {
            ?>
                    temp['datauriwidth'] = '<?php echo $superuser[ 'datauriwidth' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauriwidth'] = 0;
            <?php
        }
        ?>

        <?php
        if ( array_key_exists( 'datauriheight' , $superuser ) )
        {
            ?>
                    temp['datauriheight'] = '<?php echo $superuser[ 'datauriheight' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauriheight'] = 0;
            <?php
        }
        ?>
                superuser.push( temp );
        <?php
    }
    ?>
    <?php
    foreach ( $this->superadmin as $superadmin )
    {
        ?>
                var temp = { };
                temp['name'] = <?php echo json_encode( $superadmin[ 'name' ] ); ?>;
        <?php
        if ( array_key_exists( 'datauri' , $superadmin ) )
        {
            ?>
                    temp['datauri'] = '<?php echo $superadmin[ 'datauri' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauri'] = '';
            <?php
        }
        ?>

        <?php
        if ( array_key_exists( 'datauriwidth' , $superadmin ) )
        {
            ?>
                    temp['datauriwidth'] = '<?php echo $superadmin[ 'datauriwidth' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauriwidth'] = 0;
            <?php
        }
        ?>

        <?php
        if ( array_key_exists( 'datauriheight' , $superadmin ) )
        {
            ?>
                    temp['datauriheight'] = '<?php echo $superadmin[ 'datauriheight' ]; ?>';
            <?php
        }
        else
        {
            ?>
                    temp['datauriheight'] = 0;
            <?php
        }
        ?>
                superadmin.push( temp );
        <?php
    }
    ?>


            ordinances['dl-<?php echo $this->ordinance->id; ?>']['councilors'] = councilors;
            ordinances['dl-<?php echo $this->ordinance->id; ?>']['councilors1'] = councilors1;
            ordinances['dl-<?php echo $this->ordinance->id; ?>']['councilors2'] = councilors2;
            ordinances['dl-<?php echo $this->ordinance->id; ?>']['admin'] = superuser;
            ordinances['dl-<?php echo $this->ordinance->id; ?>']['superuser'] = superadmin;
            ordinances['dl-<?php echo $this->ordinance->id; ?>']['superadmin'] = [ {
                    'name': 'Strike Revilla',
                    'datauri': '',
                    'datauriwidth': '',
                    'datauriheight': ''
                } ];

            $( '#dl-<?php echo $this->ordinance->id; ?>' ).on( 'click', ordinances['dl-<?php echo $this->ordinance->id; ?>'], function ( eventData ) {
                var doc = new OrdinancePDF( eventData.data );
                doc.save( '<?php echo $this->escape( $this->ordinance->name ); ?>.pdf' );
            } );
    <?php
}
?>



    } );

</script>