

<tr id="n-<?php echo $this->escape( $this->q_id ); ?>">
    <td width="60%">

        <div class="bl-title">
            <h2><?php echo $this->escape( $this->question ); ?></h2>
        </div>
        <div>
            <p>Options:
            <table id="option-<?php echo $this->q_id; ?>">
                <?php
                if ( !is_null( $this->options ) && !empty( $this->options ) )
                {
                    foreach ( $this->options as $option )
                    {
                        ?>
                        <tr id="n-<?php echo $this->escape( $option[ 'opt_id' ] ); ?>">                            
                            <td>
                                <?php echo $this->escape( $option[ 'option' ] ); ?>
                            </td>                            
                        </tr>
                        <?php
                    }
                }
                else
                {
                    ?>
                    <p>There are no options for this poll.
                        <?php
                    }
                    ?>
            </table>
        </div>
        <div class="links">
            <ul>
                <li>
                    <a href="" class="action-button" id="pub-butt-<?php echo $this->q_id ?>">
                        Publish
                    </a>
                </li>                
                <li>
                    <a href="" class="action-button" id="del-butt-<?php echo $this->q_id ?>">
                         Delete
                     </a>
                </li>
            </ul>         
        </div>

    </td>
</tr>
<script type="text/javascript">
    $(document).ready(function(){
        
        var publish = function() {
             new PublishPolls('<?php echo $this->baseUrl(); ?>', 'polls', 'publish', '<?php echo $this->q_id ?>');
        };
        
        $( "#pub-butt-<?php echo $this->q_id ?>" ).on( "click", function( eventData ) 
        {
            new Confirm( 'Confirm', 'Are you sure you want to publish the survey?', 'Yes', publish );
            eventData.preventDefault();            
        });
        
        
        var deletefunc = function() {
             new Delete( '<?php echo $this->baseUrl(); ?>', 'polls', 'delete', '<?php echo $this->q_id ?>', 'polls' );
        };
        
        $( "#del-butt-<?php echo $this->q_id ?>" ).on( "click", function( eventData ) 
        {
            new Confirm( 'Confirm', 'Are you sure you want to delete the unpublished survey?', 'Yes', deletefunc );
            eventData.preventDefault();            
        });
        
    });
    
</script>