<?php $sViewFilesUrl = $this->url( array( 'controller' => 'polls' , 'action' => 'view' , 'id' => $this->q_id ) ); ?>

<tr id="n-<?php echo $this->escape( $this->q_id ); ?>">
    <td width="60%">
        <div class="bl-title">
            <h2>
                <a href="<?php echo $sViewFilesUrl; ?>"><?php echo $this->escape( $this->question ); ?></a>
            </h2>
                <?php
                if ( $this->alreadyfeatured && $this->feature )
                {
                    ?>
                    <span id="feat-mess-<?php echo $this->escape( $this->q_id ); ?>" class="important">FEATURED</span>
                    <?php
                }
                else
                {
                    ?>
                    <span id="feat-mess-<?php echo $this->escape( $this->q_id ); ?>"></span>
                    <?php
                }
                ?>
        </div>

        <div>
            <table id="option-<?php echo $this->q_id; ?>" width="100%">
                <?php
                if ( !is_null( $this->options ) && !empty( $this->options ) )
                {
                    foreach ( $this->options as $option )
                    {
                        ?>
                        <tr id="n-<?php echo $this->escape( $option[ 'opt_id' ] ); ?>">                            
                            <td width="20%">
                                <?php echo $this->escape( $option[ 'option' ] ); ?>
                            </td>
                            <td width="20%">
                                <?php echo $this->escape( $option[ 'votes' ] . '/' . $this->escape( $this->totalvotes ) ) . ' votes'; ?>
                            </td>
                            <td width="60%">

                                <?php
                                $percentage = 0;
                                $currentVotes = ( int ) $option[ 'votes' ];
                                $totalVotes = ( int ) $this->totalvotes;
                                if ( $totalVotes > 0 && $currentVotes > 0 )
                                {
                                    $percentage = ($currentVotes * 100) / $totalVotes;
                                }
                                else if ( $totalVotes > 0 )
                                {
                                    $percentage = 0;
                                }
                                else if ( $currentVotes > 0 )
                                {
                                    $percentage = 100;
                                }
                                else
                                {
                                    $percentage = 0;
                                }
                                ?>
                                <div class="percentbar" style="width: 100%;">
                                    <div style="width:  <?php echo $percentage; ?>%;"></div>
                                </div>
                            </td>
                        </tr>
                        <?php
                    }
                }
                else
                {
                    ?>
                    <p>There are no options for this poll.
                        <?php
                    }
                    ?>
            </table>
        </div>

        <div class="links">
            <ul>
                <?php
                if ( $this->delete )
                {
                    ?>
                    <li>
                        <a href="" class="action-button" id="del-butt-<?php echo $this->q_id ?>">
                            Delete
                        </a>
                    </li>
                    <?php
                }
                ?>

                <li>
                    <?php
                    if ( $this->feature && !$this->alreadyfeatured )
                    {
                        ?>
                        <a href="" class="action-button" id="feat-butt-<?php echo $this->q_id ?>">
                            Set featured
                        </a>
                        <?php
                    }
                    else
                    {
                        ?>
                        <a href=""id="feat-butt-<?php echo $this->q_id ?>"></a>
                        <?php
                    }
                    ?>
                </li>

            </ul>         
        </div>

    </td>
</tr>
<script type="text/javascript">
    $( document ).ready( function() {

        var deletefunc = function() {
            new Delete( '<?php echo $this->baseUrl(); ?>', 'polls', 'delete', '<?php echo $this->q_id ?>', 'polls' );
        };

        $( "#del-butt-<?php echo $this->q_id ?>" ).on( "click", function( eventData )
        {
            new Confirm( 'Confirm', 'Are you sure you want to delete the published survey?', 'Yes', deletefunc );
            eventData.preventDefault();
        } );

        var featuredfunc = function() {
            new FeaturePolls( '<?php echo $this->baseUrl(); ?>', 'polls', 'feature', '<?php echo $this->q_id ?>', 'polls' );
        };

        $( "#feat-butt-<?php echo $this->q_id ?>" ).on( "click", function( eventData )
        {
            new Confirm( 'Confirm', 'Are you sure you want to set this survey as featured in home page?', 'Yes', featuredfunc );
            eventData.preventDefault();
        } );

    } );
</script>