<div>
    <h1><?php echo $this->escape($this->question)?></h1>
    <table>
        <?php 
            if(!is_null($this->options) &&!empty($this->options))
            {
                foreach ($this->options as $option)
                {
            ?>
                    <tr>                            
                        <td>
                            <?php echo $this->escape($option['option']);?>
                        </td>                            
                    </tr>
            <?php
                }
            }
            else 
            {?>
                <p>There are no options for this poll.
            <?php
            }
            ?>
    </table>
</div>