<div id="content">
    <div id="content-wrap">
        <div id="title-bar">
            <h1><?php echo $this->escape( $this->title ); ?></h1>
            <a href="<?php echo $this->url( array( 'controller' => 'polls' , 'action' => 'add' ) , null , true ); ?>" class="action-button">Add new</a>
        </div>
        <div>
            <table class="block-list" id="polls">

                <?php
                echo $this->partialLoop( 'polls/_pollItem.phtml' , $this->polls );
                ?>

            </table>
        </div>

    </div>   
</div>