<div class="colmask threecol">
    <div class="content-wrap">
        <div class="colmid">
            <div class="colleft">
                <div class="col1">
                    <?php
                    if ( !is_null( $this->poll ) && !empty( $this->poll ) )
                    {
                        ?>
                        <div id="title-category-bar">
                            <h1>ANO SA TINGIN MO?</h1>
                        </div>
                        <div id="poll-header"><div id="poll-header-content">Poll</div></div>
                        <div id="poll">
                            <div id="title-bar">
                                <h1 id="article-title"><?php echo $this->escape( $this->poll[ 'question' ] ); ?></h1>
                            </div>        
                            <div id="poll-options-<?php echo $this->poll[ 'q_id' ]; ?>" class="poll-options">
                                <ul>
                                    <?php
                                    $i = 0;
                                    foreach ( $this->poll[ 'options' ] as $option )
                                    {
                                        ?>
                                        <li>
                                            <?php
                                            if ( $i == 0 )
                                            {
                                                ?>
                                                <input type="radio" name="poll-radio" checked="true" value="<?php echo $this->escape( $option[ 'opt_id' ] ); ?>" class="signup-radio"/>
                                                <?php
                                            }
                                            else
                                            {
                                                ?>
                                                <input type="radio" name="poll-radio" value="<?php echo $this->escape( $option[ 'opt_id' ] ); ?>" class="signup-radio"/>
                                                <?php
                                            }
                                            ?>

                                            <?php echo $this->escape( $option[ 'option' ] ); ?>
                                        </li>
                                        <?php
                                        $i++;
                                    }
                                    ?>
                                </ul>
                            </div>
                            <div class="links">
                                <ul>
                                    <?php
                                    if ( $this->vote && !$this->alreadyvoted )
                                    {
                                        ?>
                                        <li id="poll-button-changer"></li>
                                        <?php
                                    }
                                    else if ( !$this->vote )
                                    {
                                        ?>
                                        <li id="poll-button-changer">Please log in to vote.</li>
                                        <?php
                                    }
                                    else if ( $this->alreadyvoted )
                                    {
                                        ?>
                                        <li id="poll-button-changer">You have already voted for this poll.
                                            <span><a class="action-button" href="<?php echo $this->baseUrl( 'polls/published' ); ?>">Show all polls</a></span></li>
                                        <?php
                                    }
                                    ?>
                                </ul>
                            </div>
                        </div>
                        <div id="votes-header"><div id="votes-header-content">Results</div></div>
                        <div id="votes">
                            <table id="option-<?php echo $this->poll[ 'q_id' ]; ?>" width="50%">
                                <?php
                                if ( !is_null( $this->poll[ 'options' ] ) && !empty( $this->poll[ 'options' ] ) )
                                {
                                    ?>
                                    <tr><td id="t-<?php echo $this->poll[ 'q_id' ];?>" colspan="3"><?php echo $this->escape( $this->poll[ 'totalvotes' ] ).' votes'; ?></td></tr><?php
                                    foreach ( $this->poll[ 'options' ] as $option )
                                    {
                                        ?>
                                        <tr id="n-<?php echo $this->escape( $option[ 'opt_id' ] ); ?>">                            
                                            <td width="20%">
                                                <?php echo $this->escape( $option[ 'option' ] ); ?>
                                            </td>
                                            <td width="20%">
                                                <?php echo $this->escape( $option[ 'votes' ]); ?>
                                            </td>
                                            <td width="60%">

                                                <?php
                                                $percentage = 0;
                                                $currentVotes = ( int ) $option[ 'votes' ];
                                                $totalVotes = ( int ) $this->poll[ 'totalvotes' ];
                                                if ( $totalVotes > 0 && $currentVotes > 0 )
                                                {
                                                    $percentage = ($currentVotes * 100) / $totalVotes;
                                                }
                                                else if ( $totalVotes > 0 )
                                                {
                                                    $percentage = 0;
                                                }
                                                else if ( $currentVotes > 0 )
                                                {
                                                    $percentage = 100;
                                                }
                                                else
                                                {
                                                    $percentage = 0;
                                                }
                                                ?>
                                                <div class="percentbar" style="width: 100%;">
                                                    <div style="width:  <?php echo $percentage; ?>%;"></div>
                                                </div>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                }
                                else
                                {
                                    ?>
                                    <p>There are no options for this poll.
                                        <?php
                                    }
                                    ?>
                            </table>
                        </div>

                        <?php
                    }
                    ?>
                </div>
                <div class="col2">
                    <div id="visit">
                        <a id="visit_link" href="">
                            <img id="banner-img" alt="Bacoor City Government" src="<?php echo $this->baseUrl( 'img/bacoor.png' ); ?>" width="100%"/>
                        </a>
                    </div>
                    <div id="ordinances-header">
                        <div id="ordinances-header-content">
                            City Ordinances
                        </div>
                    </div>
                    <div id="ordinances-list">
                        <ul>
                            <?php
                            echo $this->partialLoop( 'index/_ordinanceItem.phtml' , $this->ordinances );
                            ?>
                        </ul>
                    </div>
                    <!-- Column 2 end -->
                </div>
                <div class="col3">
                    <!-- Column 3 start -->
                    <div id="ads">
                        <a href="">
                            <img src=<?php echo $this->baseUrl( 'img/vote.png' ); ?> alt="Vote!" width="100%"/>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $( document ).ready( function() {
        
        $( '#visit_link' ).on( 'click', { url: "http://www.cavite.gov.ph/home/index.php/cities-and-municipalities/district-ii/bacoor-city" },
        function( eventObject ) {
            window.open( eventObject.data.url );
            return false;
        } );

<?php
if ( !is_null( $this->poll ) && !empty( $this->poll ) )
{
    if ( $this->vote && !$this->alreadyvoted )
    {
        ?>
                $( '#poll-button-changer' ).empty().append( $( '<span/>' ).append( $( '<a/>', {
                    html: "Vote",
                    href: "",
                    "class": "action-button"
                } ) ) );

                $( '#poll-button-changer' ).find( 'a' ).on( 'click', {
                    url: '<?php echo $this->baseUrl(); ?>',
                    controller: 'polls',
                    action: 'vote',
                    questionId: '<?php echo $this->poll[ 'q_id' ] ?>',
                    radioGroupName: 'poll-radio',
                    containerName: 'poll-options',
                    buttonContainerName: 'poll-button-changer',
                    additionalLink: '<?php echo $this->baseUrl( 'polls/published' ); ?>'
                }, function( event ) {
                    event.preventDefault();
                    new VoteFromView( event.data.url, event.data.controller, event.data.action,
                            event.data.questionId, event.data.radioGroupName,
                            event.data.containerName, event.data.buttonContainerName, event.data.additionalLink );
                } );
        <?php
    }
}
?>

    } );

</script>
