<div id="content">
    <div id="content-wrap">
        <div>
            <iframe id="preview-pane" class="preview-pane" width="100%" height="650" frameborder="0" style="position:relative;"></iframe>
        </div>
    </div>   
</div>
<script type="text/javascript">
    $( document ).ready( function() {

        var doc = new jsPDF( 'p', 'pt', 'a4' );
        var pageHeight = 842;
        var pageWidth = 595;
        var marginBottom = 50;
        var pageMaxY = pageHeight - marginBottom;

        var contentWidth = pageWidth * 0.75;
        var gutterWidth = pageWidth * 0.25;

        var contentInnerMargin = 10;
        var firstPageStartY = 200;
        var otherPageStartY = 50;

        var gutterGap = 50;
        doc.addImage( '<?php echo $this->logoURI; ?>', 32, 35, 80, 80 );

        doc.setFont( 'times' );
        doc.setFontSize( 9 );
        doc.customText( "Republic of the Philippines", { align: "center", 
            relativeWidth: contentWidth, xoffset: gutterWidth }, 0, 60 );

        doc.setFontType( 'bold' );
        doc.setFont( 'helvetica' );
        doc.setFontSize( 10 );
        doc.customText( "CITY OF BACOOR", { align: "center", 
            relativeWidth: contentWidth, xoffset: gutterWidth }, 0, 75 );

        doc.setFont( 'times' );
        doc.setFontType( 'normal' );
        doc.setFontSize( 10 );
        doc.customText( "Province of Cavite", { align: "center", 
            relativeWidth: contentWidth, xoffset: gutterWidth }, 0, 90 );

        doc.setFontType( 'bold' );
        doc.setFontSize( 11 );
        doc.customText( "OFFICE OF THE SANGGUNIANG PANGLUNGSOD", { align: "center", 
            relativeWidth: contentWidth, xoffset: gutterWidth }, 0, 115 );

        doc.setFont( 'helvetica' );
        doc.setFontType( 'normal' );
        doc.setFontSize( 11 );

        var titlelines = doc.splitTextToSize( <?php echo json_encode( $this->escape( $this->ordinance->name ) ); ?>, 300 );
        var titlelinegap = 12;
        var titleIndex = 0;
        for ( ; titleIndex < titlelines.length; titleIndex++ )
        {
            doc.customText( titlelines[titleIndex], { align: "center", 
            relativeWidth: contentWidth, xoffset: gutterWidth }, 0, 150 + titlelinegap * titleIndex );
        }
        firstPageStartY = 170 + titlelinegap * titleIndex;

        doc.setFont( 'helvetica' );
        doc.setFontSize( 8 );
        //doc.text( 55, 135, 'District I:' );

<?php
$count = 0;
foreach ( $this->councilors as $value )
{
    ?>

            doc.addImage( '<?php echo $value[ 'signature-datauri' ]; ?>', 'png', 10,
                    160 + gutterGap * parseInt( '<?php echo $count; ?>' ),
                    parseInt( '<?php echo $value[ 'signature-datauri-width' ]; ?>' ),
                    parseInt( '<?php echo $value[ 'signature-datauri-height' ]; ?>' ) );
            doc.setFontType( 'bold' );
            doc.text( 10, 190 + gutterGap * parseInt( '<?php echo $count; ?>' ), 'HON. <?php echo $value[ 'name' ]; ?>'.toUpperCase() );
            doc.setFontType( 'normal' );
            doc.text( 10, 200 + gutterGap * parseInt( '<?php echo $count; ?>' ), 'City Councilor' );
    <?php
    $count++;
}
?>

        var line = <?php echo json_encode( $this->escape( $this->ordinance->summary ) ); ?>;

        doc.setFontSize( 7 );
        doc.setFont( 'helvetica' );
        doc.setFontType( 'normal' );

        var lines = doc.splitTextToSize( line, 400 );
        var lineCount = 0;
        var startY = firstPageStartY;
        var lineGap = 10;

        for ( var i = 0; i < lines.length; i++ )
        {
            var nextY = startY + lineGap * lineCount;
            if ( nextY > pageMaxY )
            {
                lineCount = 0;
                startY = otherPageStartY;
                nextY = otherPageStartY;

                doc.addPage();
                doc.addImage( '<?php echo $this->logoURI; ?>', 32, 35, 80, 80 );
<?php
$n = 0;
foreach ( $this->councilors as $value )
{
    ?>

                    doc.addImage( '<?php echo $value[ 'signature-datauri' ]; ?>', 'png', 10,
                            160 + gutterGap * parseInt( '<?php echo $n; ?>' ),
                            parseInt( '<?php echo $value[ 'signature-datauri-width' ]; ?>' ),
                            parseInt( '<?php echo $value[ 'signature-datauri-height' ]; ?>' ) );
                    doc.setFontType( 'bold' );
                    doc.text( 10, 190 + gutterGap * parseInt( '<?php echo $n; ?>' ), 'HON. <?php echo $value[ 'name' ]; ?>'.toUpperCase() );
                    doc.setFontType( 'normal' );
                    doc.text( 10, 200 + gutterGap * parseInt( '<?php echo $n; ?>' ), 'City Councilor' );
    <?php
    $n++;
}
?>
            }

            doc.text( gutterWidth + contentInnerMargin, nextY, lines[i] );
            lineCount++;
        }


        var string = doc.output( 'datauristring' );
        $( '.preview-pane' ).attr( 'src', string );

    } );
</script>
