<div id="content">
    <div id="content-wrap">
        <h1>Edit "About Us" Content</h1>

        <?php
        if ( !is_null( $this->message ) && !empty( $this->message ) )
        {
            ?>
            <div id="flashmessage" class="flashmessage">
                <ul>
                    <li><?= $this->message; ?></li>
                </ul>
            </div>
            <?php
        }
        ?>

        <div id="editaboutus">
            <?php echo $this->form; ?>
        </div>

        <div class="image-row"></div>

    </div>
</div>

<script type="text/javascript">
    $( document ).ready( function() {

        var saveAdd = function() {
            $( "#saveAdd" ).submit();
        };

        $( "#Save" ).on( 'click', function( eventData )
        {
            new Confirm( 'Confirm', 'Are you sure you want save your changes?', 'Yes', saveAdd );
            eventData.preventDefault();
        } );

        //images
        $( '#images' ).parent().append( $( '<span class="caption-item"/>' ) );
        $( '#images' ).on( 'change', function() {
            $( '.caption-item' ).empty().append( $( '<span class="caption-field">\n\
            <label>Add caption:</label>\n\
            <input type="text" id="caption" name="caption"></input></span>' ).css( 'marginLeft', '10px' ) );
        } );

        var images = <?php echo json_encode( $this->images ) ?>;
        var ul = $( '<ul/>' ).css( {
            'list-style': 'none',
            'margin': 0,
            'padding': 0

        } );

        var deletefunc = function( id, filename ) {
            new DeleteFile( '<?php echo $this->baseUrl(); ?>', 'about', 'delete', id, filename );
        };

        for ( i = 0; i < images.length; i++ )
        {
            var a = $( '<a/>', { 'class': 'grouped_elements', rel: 'group', href: images[i]['path'], id: 'im-' + i } );
            var img = $( '<img/>', { src: images[i]['path'] } ).width( images[i]['width'] ).height( images[i]['height'] );
            var li = $( '<li/>', { id: 'li-' + i, 'class': 'grouped_lists' } );

            var deleteButt = $( '<a/>', { 'class': 'action-button', href: '', id: 'i-' + i } ).append( 'x' )
                    .on( 'click', { id: i, path: images[i]['basename'] }, function( eventData ) {
                        new Confirm( 'Confirm', 'Are you sure you want to delete the image?', 'Yes', function() {
                            deletefunc( eventData.data.id, eventData.data.path );
                        } );
                        eventData.preventDefault();
                    } );

            li.append( $( '<div/>' ).append( deleteButt ).css( 'padding-bottom', '5px' ) );
            li.append( $( '<div/>' ).append( a.append( img ) ) );
            li.append( $( '<div/>', { width: images[i]['width'] + 'px', 'class': 'wrapword' } ).append( images[i]['caption'] ) );
            ul.append( li );
        }
        $( '.image-row' ).append( ul );
        $( "a.grouped_elements" ).fancybox();
    } );
</script>