<h3><?php echo $this->escape($this->title)?></h3>
<br/>
    <?php echo $this->formmessage?>
<br/>
<ul>
<?php
    foreach($this->formresponse as $message):
?>
        <li><?php echo $this->escape($message);?></li>
<?php
    endforeach;
?>
</ul>

<form method="POST" action="<?php echo $this->escape($this->url);?>">

    <div id="contactus-form">
        
        <div class="">UPDATE 'CONTACT US' INFORMATION</div>

        <div id="contactus-textarea">            
            <textarea id="contactus-text" class="textarea" name="contactus-text" rows="30" cols="140"></textarea>                        
        </div>
       
        <div>
            <input id="submit-butt" name="submit-butt" type="submit" value="Submit">
        </div>
    </div>
</form>
<script type="text/javascript">
$( document ).ready(function() {
    $('#contactus-text').val('<?php echo $this->escape($this->post['contactus-text']);?>');
});
</script>