<div id="content">
    <div id="content-wrap">

        <div id="title-bar">
            <h2><?php echo $this->escape( $this->team->name ); ?> </h2>            
        </div>

        <div>
            <h3>Team Information</h3>
        </div>
        <div>
            <table>
                <tr>
                    <td>Description:</td>
                    <td><?php echo $this->escape( $this->team->description ); ?></td>
                </tr>
            </table>
        </div>

    </div>   
</div>