<div id="content">
    <div id="content-wrap">

        <div id="title-bar">
            <h1>Edit House</h1>
        </div>
        <?php
        if ( !is_null( $this->message ) && !empty( $this->message ) )
        {
            ?>
            <div id="flashmessage" class="flashmessage">
                <ul>
                    <li><?= $this->message; ?></li>
                </ul>
            </div>
            <?php
        }
        ?>

        <div id="edit-house-form">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    $( document ).ready( function () {

        $( "#save" ).on( 'click', function ( eventData )
        {
            new Confirm( 'Confirm', 'Are you sure you want to save the team details?', 'Yes', function () {
                $( "#edit-house" ).submit();
            } );
            eventData.preventDefault();
        } );

    } );
</script> 