<div id="content">
    <div id="content-wrap">
        <h1>Edit Map</h1>

        <?php
        if ( !is_null( $this->message ) && !empty( $this->message ) )
        {
            ?>
            <div id="flashmessage" class="flashmessage">
                <ul>
                    <li><?= $this->message; ?></li>
                </ul>
            </div>
            <?php
        }
        ?>

        <div id="edit-map">
            <?php echo $this->form; ?>
        </div>

        <div class="image-row"></div>
    </div>
</div>

<script type="text/javascript">
    $( document ).ready( function() {

        var saveAdd = function() {
            $( "#saveAdd" ).submit();
        };

        $( "#Save" ).on( 'click', function( eventData )
        {
            new Confirm( 'Confirm', 'Are you sure you want save your changes?', 'Yes', saveAdd );
            eventData.preventDefault();
        } );

        //images
        var images = <?php echo json_encode( $this->images ) ?>;
        var ul = $( '<ul/>' ).css( {
            'list-style': 'none',
            'margin': 0,
            'padding': 0

        } );

        var deletefunc = function( filename, id, postid ) {
            new DeletePostFile( '<?php echo $this->baseUrl(); ?>', 'map', 'deletefile', filename, id, postid );
        };


        for ( i = 0; i < images.length; i++ )
        {
            console.log( images[i]['path'] );

            var a = $( '<a/>', { 'class': 'grouped_elements', rel: 'group', href: images[i]['path'], id: 'im-' + i } );
            var img = $( '<img/>', { src: images[i]['path'] } ).width( images[i]['width'] ).height( images[i]['height'] );

            var li = $( '<li/>', { id: 'li-' + i } ).css( { 'display': 'inline' } );
            li.append( a.append( img ) );

            //delete button
            var deleteButt = $( '<a/>', { 'class': 'action-button', href: '', id: 'i-' + i } ).append( 'Delete' )
                    .on( 'click', { path: images[i]['basename'], id: i, postid: images[i]['postid'] }, function( eventData ) {
                        new Confirm( 'Confirm', 'Are you sure you want to delete the image?', 'Yes', function() {
                            deletefunc( eventData.data.path, eventData.data.id, eventData.data.postid );
                        } );
                        eventData.preventDefault();
                    } );

            li.append( deleteButt );
            ul.append( li );
        }
        $( '.image-row' ).append( ul );
        $( "a.grouped_elements" ).fancybox();

    } );
</script> 